version: "3.5"
services: 

  app:
    image: php:8.1
    command: php -S 0.0.0.0:8000 /app/index.php
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  composer:
    image: composer/composer:2.3.9
    command: ["composer","install"]
    depends_on: ["app"]
    volumes:
      - .:/app
